[package]
name = "rssss"
version = "0.1.0"
authors = ["zaneli <shun.otani@gmail.com>"]

[dependencies]
actix = "0.7"
actix-web = { version="0.7", features=["ssl"] }
listenfd = "0.3"

futures = "0.1"
failure = "0.1"
bytes = "0.4"
log = "0.4"
simple_logger = "1.0"
xml-rs = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
scraper = "*"
